/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f746xx.h"


void Delay() {
    for (uint32_t i = 0; i < 500000/2; i++) {
        // Simple delay loop
    }

}
int main(void)
{

    GPIO_Handle_t GpioBGreen;
    GPIO_Handle_t GpioCButton;

    GpioBGreen.pGPIOx = GPIOB;
    GpioCButton.pGPIOx = GPIOC;
    GpioBGreen.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_0;
    GpioBGreen.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
    GpioBGreen.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;

    GpioCButton.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_IN; // Input mode for button
    GpioCButton.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_13; // Button pin
    GpioCButton.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST; // Fast speed for button
    GpioCButton.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD; // No pull-up or pull-down for button


    // Enable the peripheral clock
    GPIO_PeriClockControl(GPIOB, ENABLE);
    GPIO_PeriClockControl(GPIOC, ENABLE);


    // Initialize the pin
    GPIO_Init(&GpioCButton);
    GPIO_Init(&GpioBGreen);


    while (1) {

		if (GPIO_ReadFromInputPin(GPIOC, GPIO_PIN_13) == 1) {
		    Delay();
			GPIO_ToggleOutputPin(GPIOB, GPIO_PIN_0); // Toggle the green LED pin

		}

    }

}


