/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f746xx.h"


void Delay() {
    for (uint32_t i = 0; i < 500000/2; i++) {
        // Simple delay loop
    }

}
int main(void)
{

    GPIO_Handle_t gpioA;
    GPIO_Handle_t gpioB ={0};

    gpioA.pGPIOx = GPIOA;
    gpioB.pGPIOx = GPIOB;

   // gpioA.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_IN;
    gpioB.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
   // gpioA.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;
   // gpioB.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
    gpioA.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_3;
    gpioB.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_0;

    GPIO_PeriClockControl(GPIOA,ENABLE);
    GPIO_PeriClockControl(GPIOB,ENABLE);
    GPIO_Init(&gpioA);
    GPIO_Init(&gpioB);


    while(1) {
    	if(GPIO_ReadFromInputPin(GPIOA,GPIO_PIN_3) == 1) {
        Delay();
        GPIO_ToggleOutputPin(GPIOB,GPIO_PIN_0);
    }

}

}
